[package]
name = "test_shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "test_shared"
crate_type = ["dylib"]

[dependencies]
